#!/bin/bash
source "$(dirname "$0")/shared-functions.sh"
emit_url "help"

echo ""
typewriter "${PURPLE}commands${RESET}"
animated_separator "-" 10 "$PURPLE"
typewriter "${BLUE}  about           ${WHITE}learn about me${RESET}"
typewriter "${BLUE}  contact         ${WHITE}my email and links to socials${RESET}"
typewriter "${BLUE}  resume          ${WHITE}view my resume${RESET}"
typewriter "${BLUE}  projects        ${WHITE}explore my projects (you can use vim/nvim!)${RESET}"
typewriter "${BLUE}  blog            ${WHITE}posts i've written${RESET}"
typewriter "${BLUE}  <project>       ${WHITE}jump straight to a project page:${RESET}"
typewriter "${DIM}                  harness, hone, flt, agentelo, term-site,${RESET}"
typewriter "${DIM}                  trade-up-bot, studyspot, stm32-games, dotfiles,${RESET}"
typewriter "${DIM}                  tetrio-tui, deck, hone-a-drone, gepa-ts, also${RESET}"
typewriter "${BLUE}  theme           ${WHITE}re-theme this site — 463 schemes, live fzf preview${RESET}"
typewriter "${DIM}                  theme <name> · theme dark|light · theme reset${RESET}"
typewriter "${BLUE}  boot            ${WHITE}replay the intro animation (boot <name> to pick one:${RESET}"
typewriter "${DIM}                  braille-fire, starfield-warp, braille-plasma, logo-decode)${RESET}"
typewriter "${BLUE}  gui             ${WHITE}the point-and-click version (for mouse users)${RESET}"
typewriter "${BLUE}  help            ${WHITE}you already used it once...${RESET}"
typewriter "${BLUE}  home            ${WHITE}back to the main page!${RESET}"
echo ""
typewriter "${DIM}you can use most commands you are familiar with inside the terminal like cd, ls, etc.${RESET}"
typewriter "${DIM}other tools like ${PURPLE}nvim${RESET}${DIM}, ${PURPLE}git${RESET}${DIM}, ${PURPLE}grep${RESET}${DIM}, ${PURPLE}figlet${RESET}${DIM} and many more are available!${RESET}"
echo ""
