// Terminal theme: Hardcore
// Auto-generated by scripts/generate-theme.sh — do not edit by hand.
// Re-run after changing your Ghostty theme: ./scripts/generate-theme.sh

module.exports = {
  primary: '#a6e22e', // colour2 — primary accent
};
