// Terminal theme: Hardcore
// Auto-generated by scripts/generate-theme.sh — do not edit by hand.
// Re-run after changing your Ghostty theme: ./scripts/generate-theme.sh

export const terminalTheme = {
  background: '#121212',
  foreground: '#a0a0a0',
  cursor: '#bbbbbb',
  cursorAccent: '#ffffff',
  selection: '#453b39',
  selectionForeground: '#b6bbc0',

  black:         '#1b1d1e',   // colour0
  red:           '#f92672',   // colour1
  green:         '#a6e22e',   // colour2
  primary:       '#a6e22e',   // colour2 — primary accent
  yellow:        '#fd971f',   // colour3
  blue:          '#66d9ef',   // colour4
  magenta:       '#9e6ffe',   // colour5
  cyan:          '#5e7175',   // colour6
  white:         '#ccccc6',   // colour7

  brightBlack:   '#505354',   // colour8
  brightRed:     '#ff669d',   // colour9
  brightGreen:   '#beed5f',  // colour10
  brightYellow:  '#e6db74',  // colour11
  brightBlue:    '#66d9ef',  // colour12
  brightMagenta: '#9e6ffe',  // colour13
  brightCyan:    '#a3babf',  // colour14
  brightWhite:   '#f8f8f2',  // colour15
};

export const terminalConfig = {
  fontFamily: '"JetBrainsMono Nerd Font Mono", "JetBrainsMono Nerd Font", "JetBrains Mono", "Fira Code", "Monaco", "Consolas", monospace',
  fontSize: 12,
  fontWeight: 'normal' as const,
  fontWeightBold: 'bold' as const,
  lineHeight: 1.0,

  cursorBlink: true,
  cursorStyle: 'block' as const,
  bellStyle: 'none' as const,

  scrollback: 10000,
  fastScrollModifier: 'alt' as const,

  allowProposedApi: true,
  allowTransparency: false,
  macOptionIsMeta: true,

  cols: 120,
  rows: 30,

  theme: terminalTheme,
};
