#!/usr/bin/env python3
"""Regenerate frontend/src/config/themes.ts from the local Ghostty theme dir.

One-liner to change the site defaults:
  ./scripts/generate-themes-lib.py --dark "iTerm2 Tango Dark" --light "iTerm2 Tango Light"

Defaults are baked into the generated file; visitors pick any theme live via
the in-shell `theme` command (OSC 9995) or the header light/dark toggle.
"""
import argparse, json, os, re, sys

GHOSTTY_THEMES_DIR = "/Applications/Ghostty.app/Contents/Resources/ghostty/themes"
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_FILE = os.path.join(REPO_ROOT, "frontend/src/config/themes.ts")

DEFAULT_DARK = "iTerm2 Tango Dark"
DEFAULT_LIGHT = "iTerm2 Tango Light"

def parse_theme(path):
    d = {"palette": {}}
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        m = re.match(r"palette\s*=\s*(\d+)\s*=\s*#?([0-9a-fA-F]{6})", line)
        if m:
            d["palette"][int(m.group(1))] = "#" + m.group(2).lower()
            continue
        k, v = (s.strip() for s in line.split("=", 1))
        if k in ("background", "foreground", "cursor-color", "cursor-text",
                 "selection-background", "selection-foreground") and re.match(r"#?[0-9a-fA-F]{6}$", v):
            d[k] = "#" + v.lstrip("#").lower()
    return d

def luminance(hexc):
    h = hexc.lstrip("#")
    r, g, b = (int(h[i:i+2], 16) / 255 for i in (0, 2, 4))
    f = lambda c: c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dark", default=DEFAULT_DARK)
    ap.add_argument("--light", default=DEFAULT_LIGHT)
    args = ap.parse_args()

    themes = {}
    for fn in sorted(os.listdir(GHOSTTY_THEMES_DIR)):
        p = os.path.join(GHOSTTY_THEMES_DIR, fn)
        if not os.path.isfile(p):
            continue
        t = parse_theme(p)
        if "background" not in t or "foreground" not in t or len(t["palette"]) < 16:
            continue
        pal = [t["palette"][i] for i in range(16)]
        themes[fn] = {
            "background": t["background"], "foreground": t["foreground"],
            "cursor": t.get("cursor-color", t["foreground"]),
            "cursorAccent": t.get("cursor-text", t["background"]),
            "selection": t.get("selection-background", pal[8]),
            "selectionForeground": t.get("selection-foreground", t["foreground"]),
            "palette": pal,
            "mode": "light" if luminance(t["background"]) > 0.35 else "dark",
        }

    for name, flag in ((args.dark, "--dark"), (args.light, "--light")):
        if name not in themes:
            sys.exit(f"error: {flag} theme {name!r} not found in {GHOSTTY_THEMES_DIR}")
    if themes[args.dark]["mode"] != "dark":
        sys.exit(f"error: --dark theme {args.dark!r} is classified light")
    if themes[args.light]["mode"] != "light":
        sys.exit(f"error: --light theme {args.light!r} is classified dark")

    slots = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
             "brightBlack", "brightRed", "brightGreen", "brightYellow",
             "brightBlue", "brightMagenta", "brightCyan", "brightWhite"]
    lines = []
    for name, t in themes.items():
        parts = [f"background:'{t['background']}'", f"foreground:'{t['foreground']}'",
                 f"cursor:'{t['cursor']}'", f"cursorAccent:'{t['cursorAccent']}'",
                 f"selection:'{t['selection']}'", f"selectionForeground:'{t['selectionForeground']}'"]
        parts += [f"{slots[i]}:'{t['palette'][i]}'" for i in range(16)]
        parts.append(f"mode:'{t['mode']}'")
        lines.append(f"  {json.dumps(name)}: {{ {', '.join(parts)} }},")

    out = f"""// Terminal theme library — {len(themes)} Ghostty themes.
// Auto-generated by scripts/generate-themes-lib.py — do not edit by hand.
// Change the site defaults:
//   ./scripts/generate-themes-lib.py --dark "<name>" --light "<name>"

export const DEFAULT_DARK_THEME = {json.dumps(args.dark)};
export const DEFAULT_LIGHT_THEME = {json.dumps(args.light)};

export interface ThemeEntry {{
  background: string; foreground: string; cursor: string; cursorAccent: string;
  selection: string; selectionForeground: string;
  black: string; red: string; green: string; yellow: string; blue: string;
  magenta: string; cyan: string; white: string;
  brightBlack: string; brightRed: string; brightGreen: string; brightYellow: string;
  brightBlue: string; brightMagenta: string; brightCyan: string; brightWhite: string;
  mode: 'dark' | 'light';
}}

export const themes: Record<string, ThemeEntry> = {{
{chr(10).join(lines)}
}};

export const themeNames: string[] = Object.keys(themes);

export function themeNamesForMode(mode: 'dark' | 'light'): string[] {{
  return themeNames.filter((n) => themes[n].mode === mode);
}}
"""
    with open(OUT_FILE, "w") as f:
        f.write(out)
    print(f"wrote {OUT_FILE}: {len(themes)} themes, defaults dark={args.dark!r} light={args.light!r}")

    # Keep the backend's accent (admin panel) in sync with the dark default.
    backend_out = os.path.join(REPO_ROOT, "backend/theme.js")
    with open(backend_out, "w") as f:
        f.write(f"""// Terminal theme: {args.dark}
// Auto-generated by scripts/generate-themes-lib.py — do not edit by hand.

module.exports = {{
  primary: '{themes[args.dark]["palette"][2]}', // colour2 — primary accent
}};
""")
    print(f"wrote {backend_out} (primary from {args.dark!r})")

if __name__ == "__main__":
    main()
