#!/usr/bin/env bash
# Generates frontend/src/config/terminal-theme.ts from a Ghostty theme file.
# Usage:
#   ./scripts/generate-theme.sh                 # reads theme from ~/.config/ghostty/config
#   ./scripts/generate-theme.sh GruvboxDarkHard  # use named theme explicitly
#
# After changing your Ghostty theme, run this script to keep term-site in sync.

GHOSTTY_THEMES_DIR="/Applications/Ghostty.app/Contents/Resources/ghostty/themes"
GHOSTTY_CONFIG="${HOME}/.config/ghostty/config"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$REPO_ROOT/frontend/src/config/terminal-theme.ts"
BACKEND_OUT_FILE="$REPO_ROOT/backend/theme.js"

get_theme_name() {
  if [[ -n "$1" ]]; then
    echo "$1"
  else
    grep -E '^theme[[:space:]]*=' "$GHOSTTY_CONFIG" | sed 's/.*=[[:space:]]*//' | tr -d ' \r'
  fi
}

THEME_NAME=$(get_theme_name "$1")

if [[ -z "$THEME_NAME" ]]; then
  echo "Error: could not determine theme name. Set 'theme = X' in ghostty config or pass as argument." >&2
  exit 1
fi

THEME_FILE="$GHOSTTY_THEMES_DIR/$THEME_NAME"

if [[ ! -f "$THEME_FILE" ]]; then
  echo "Error: theme file not found: $THEME_FILE" >&2
  exit 1
fi

# Parse palette entries using temp files (bash 3.2 compat — no associative arrays)
TMPDIR_PARSE=$(mktemp -d)
trap "rm -rf $TMPDIR_PARSE" EXIT

bg="" fg="" cursor="" cursor_text="" sel_bg="" sel_fg=""

while IFS= read -r line; do
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line// }" ]] && continue

  key="${line%%=*}"
  rest="${line#*=}"
  key="${key// /}"
  rest="${rest# }"

  case "$key" in
    background)           bg="$rest" ;;
    foreground)           fg="$rest" ;;
    cursor-color)         cursor="$rest" ;;
    cursor-text)          cursor_text="$rest" ;;
    selection-background) sel_bg="$rest" ;;
    selection-foreground) sel_fg="$rest" ;;
    palette)
      idx="${rest%%=*}"
      color="${rest#*=}"
      echo "$color" > "$TMPDIR_PARSE/$idx"
      ;;
  esac
done < "$THEME_FILE"

slot() { cat "$TMPDIR_PARSE/$1" 2>/dev/null || echo "#000000"; }

[[ -z "$cursor" ]]      && cursor="$fg"
[[ -z "$cursor_text" ]] && cursor_text="$bg"
[[ -z "$sel_bg" ]]      && sel_bg=$(slot 8)
[[ -z "$sel_fg" ]]      && sel_fg="$fg"

cat > "$OUT_FILE" << EOF
// Terminal theme: ${THEME_NAME}
// Auto-generated by scripts/generate-theme.sh — do not edit by hand.
// Re-run after changing your Ghostty theme: ./scripts/generate-theme.sh

export const terminalTheme = {
  background: '${bg}',
  foreground: '${fg}',
  cursor: '${cursor}',
  cursorAccent: '${cursor_text}',
  selection: '${sel_bg}',
  selectionForeground: '${sel_fg}',

  black:         '$(slot 0)',   // colour0
  red:           '$(slot 1)',   // colour1
  green:         '$(slot 2)',   // colour2
  primary:       '$(slot 2)',   // colour2 — primary accent
  yellow:        '$(slot 3)',   // colour3
  blue:          '$(slot 4)',   // colour4
  magenta:       '$(slot 5)',   // colour5
  cyan:          '$(slot 6)',   // colour6
  white:         '$(slot 7)',   // colour7

  brightBlack:   '$(slot 8)',   // colour8
  brightRed:     '$(slot 9)',   // colour9
  brightGreen:   '$(slot 10)',  // colour10
  brightYellow:  '$(slot 11)',  // colour11
  brightBlue:    '$(slot 12)',  // colour12
  brightMagenta: '$(slot 13)',  // colour13
  brightCyan:    '$(slot 14)',  // colour14
  brightWhite:   '$(slot 15)',  // colour15
};

export const terminalConfig = {
  fontFamily: '"JetBrainsMono Nerd Font Mono", "JetBrainsMono Nerd Font", "JetBrains Mono", "Fira Code", "Monaco", "Consolas", monospace',
  fontSize: 12,
  fontWeight: 'normal' as const,
  fontWeightBold: 'bold' as const,
  lineHeight: 1.0,

  cursorBlink: true,
  cursorStyle: 'block' as const,
  bellStyle: 'none' as const,

  scrollback: 10000,
  fastScrollModifier: 'alt' as const,

  allowProposedApi: true,
  allowTransparency: false,
  macOptionIsMeta: true,

  cols: 120,
  rows: 30,

  theme: terminalTheme,
};
EOF

cat > "$BACKEND_OUT_FILE" << EOF
// Terminal theme: ${THEME_NAME}
// Auto-generated by scripts/generate-theme.sh — do not edit by hand.
// Re-run after changing your Ghostty theme: ./scripts/generate-theme.sh

module.exports = {
  primary: '$(slot 2)', // colour2 — primary accent
};
EOF

echo "Written: $OUT_FILE (theme: ${THEME_NAME})"
echo "Written: $BACKEND_OUT_FILE (theme: ${THEME_NAME})"
